name = "whalesurfer"
main = "index.js"
compatibility_date = "2026-07-11"

# Ativa o upload do arquivo grande como asset estático (Limite de 25MB por arquivo no plano free)
[assets]
directory = "./public"

[[routes]]
pattern = "search.gmcorporation.com.br/*"
zone_name = "gmcorporation.com.br"
